# Generated by Django 5.2.8 on 2025-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
    ]
