# Generated by Django 5.2.8 on 2025-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_users', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
